### ISSUE TITLE
Publish Error - Collecting ShotGrid Assets & Tasks

### ISSUE THREAD

**Issue by matteoveglia** [ynput/ayon-shotgrid#53]
Hi,

Putting a few tickets in today to break out separate topics.

I'm having issues publishing, in this case, from Blender to any task on a ShotGrid imported project.
![image](https://github.com/ynput/ayon-shotgrid/assets/1258632/4cc68dc0-1502-466f-8908-acdf33ee5177)

I don't get these errors if I'm publishing review media from the tray publisher, for example, so I'm not sure what the root cause of the problem is.
Could it be that Blender still uses the old publisher vs the new one with the tray tool?

This felt like a ShotGrid addon issue so I posted it here but happy to move it to the Blender addon repo if needed.

**Comment by matteoveglia** [comment]
Hmm, so I did some more digging into this.

Using the tray publisher, I selected a workfile type to publish and added the same .blend file.

This time it got a lot further (seemingly, though I realise Pyblish and Publish are built differently):
![image](https://github.com/ynput/ayon-shotgrid/assets/1258632/bf7100b2-b385-4e4d-b554-5e48365e3332)

Specifically this is the traceback in text form:
```Traceback (most recent call last):
  File "C:\Users\MatteoVeglia\AppData\Local\Ynput\AYON\dependency_packages\ayon_2310271602_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\MatteoVeglia\AppData\Local\Ynput\AYON\addons\shotgrid_0.2.9\ayon_shotgrid\plugins\publish\integrate_shotgrid_publish.py", line 74, in process
    sg_local_store["windows_path"]
TypeError: 'NoneType' object is not subscriptable
```

Lastly, the version nor a publish shows in ShotGrid (autosync is on) so I checked the server event log and I this curious error:
```2023-11-10 20:34:28 GOOD NEWS  server          Server is now ready to connect
/backend/api/thumbnails/thumbnails.py:68: RuntimeWarning: coroutine 'Connection.execute' was never awaited
  conn.execute(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-11-10 20:44:43 ERROR      server          Validation error
1 validation error for Request
body -> summary
  value is not a valid dict (type=type_error.dict)
2023-11-10 20:48:43 ERROR      anonymous       [GET] /projects/undefined/workfiles/d00ddca1804911ee8bf10c919227e150/thumbnail: Project undefined not found
2023-11-10 20:48:51 ERROR      server          GraphQL: /ayon_server/types.py:83 (project/folders) Name 'N/A' does not match regex '^[a-zA-Z0-9_][a-zA-Z0-9_ \-]{1,64}[a-zA-Z0-9_]$'
```
