### ISSUE TITLE
No Playable Media/Thumbnail on Published Versions

### ISSUE THREAD

**Issue by matteoveglia** [ynput/ayon-shotgrid#54]
Breaking this issue out from a larger one
----------
So I went to the traypublisher tool, grabbed a 10 second .mp4 of Big Buck Bunny and went to publish it as a Render type.
The publish went through perfectly and I saw it run ffmpeg to extract a reviewable from the .mp4, however, in ShotGrid I see no uploaded media nor path under the "Path To [...]" fields; also no Ayon ID or Sync Status?
![image](https://github.com/ynput/ayon-shotgrid/assets/1258632/07b843f3-74b3-471d-8fcc-7de361bdea80)

_Originally posted by @matteoveglia in https://github.com/ynput/ayon-shotgrid/issues/22#issuecomment-1797927166_

**Comment by matteoveglia** [comment]
Update on this, Fabia helped me a little more and saw that the 'shotgridreview' tag was indeed in the ShotGrid publish code so I tried it.

Okay, so to be clear first, I have already managed to perform a successful publish of a test plate asset without the shotgridreview tag added. It made a version in SG along with a published file and worked just fine, of course it didn’t upload the movie though.

All I changed in this variable is adding that tag but this is the error on the “ShotGrid Version” integrate stage:
```
INFO: Create Shotgrid version: {'id': 8498, 'project': {'id': 155, 'name': 'LibraryTest', 'type': 'Project'}, 'entity': {'id': 1445, 'name': 'TestAsset', 'type': 'Asset'}, 'code': 'LIBTST_LibraryTest_TestAsset_Concept_v008', 'sg_task': {'id': 6295, 'name': 'Concept', 'type': 'Task'}, 'type': 'Version'}
INFO: Upload review: O:\Projects\LibraryTest\TestAsset\publish\plate\plateMain\v008\LIBTST_TestAsset_plateMain_v008_h264.mov for version shotgrid 8498
Traceback (most recent call last):
  File "C:\Users\MatteoVeglia\AppData\Local\Ynput\AYON\dependency_packages\ayon_2310271602_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\MatteoVeglia\AppData\Local\Ynput\AYON\addons\shotgrid_0.2.7\ayon_shotgrid\plugins\publish\integrate_shotgrid_version.py", line 63, in process
    self.sg_session.upload(
AttributeError: 'IntegrateShotgridVersion' object has no attribute 'sg_session'
```
I don’t care to share the full paths as this is all totally test data on a test sandbox.

Strange error though, it suggests that the code never created a connection to SG but I can confirm that a version was made from this publish so I’m at a loss.

**Comment by jakubjezek001** [comment]
Hey guys, sorry for the long quiet pause. Yeah this is currently been fixed in #83 please give it a go and test it. You will need to have latest ayon-core with server ideally.
