### ISSUE TITLE
Syncing fails 

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/ayon-shotgrid#85]
Syncing fails when these conditions are not met in Project Entity tracking

Tracking Settings:
Episode: Hierarchy: Episode (flat hierarchy)
Sequence: Hierarchy: Episode > Sequence
Shot: Hierarchy: Episode > Sequence > Shot

With any other settings it fails with errors:

```
2024-04-10 14:43:27     Traceback (most recent call last):
2024-04-10 14:43:27       File "/service/processor/processor.py", line 173, in start_processing
2024-04-10 14:43:27         handler.process_event(
2024-04-10 14:43:27       File "/service/processor/handlers/shotgrid_event.py", line 42, in process_event
2024-04-10 14:43:27         hub.react_to_shotgrid_event(sg_payload["meta"])
2024-04-10 14:43:27       File "/service/ayon_shotgrid_hub/__init__.py", line 364, in react_to_shotgrid_event
2024-04-10 14:43:27         update_ayon_entity_from_sg_event(
2024-04-10 14:43:27       File "/service/ayon_shotgrid_hub/update_from_shotgrid.py", line 235, in update_ayon_entity_from_sg_event
2024-04-10 14:43:27         if not sg_ay_dict["data"].get(CUST_FIELD_CODE_ID):
2024-04-10 14:43:27                ~~~~~~~~~~^^^^^^^^
2024-04-10 14:43:27     KeyError: 'data'
```

```
2024-04-10 15:39:47     Traceback (most recent call last):
2024-04-10 15:39:47       File "/service/processor/processor.py", line 173, in start_processing
2024-04-10 15:39:47         handler.process_event(
2024-04-10 15:39:47       File "/service/processor/handlers/shotgrid_event.py", line 42, in process_event
2024-04-10 15:39:47         hub.react_to_shotgrid_event(sg_payload["meta"])
2024-04-10 15:39:47       File "/service/ayon_shotgrid_hub/__init__.py", line 353, in react_to_shotgrid_event
2024-04-10 15:39:47         create_ay_entity_from_sg_event(
2024-04-10 15:39:47       File "/service/ayon_shotgrid_hub/update_from_shotgrid.py", line 126, in create_ay_entity_from_sg_event
2024-04-10 15:39:47         if sg_ay_dict["data"][sg_parent_field] is None:
2024-04-10 15:39:47            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
2024-04-10 15:39:47     KeyError: 'sg_sequence'
2024-04-10 15:39:47     
2024-04-10 15:39:47 
2024-04-10 15:39:47 2024-04-10 13:39:47 ERROR      403 Client Error: Forbidden for url: http://server:5000/api/events/c9ad7802f73f11ee988f0242ac120002
2024-04-10 15:39:47 
2024-04-10 15:39:47     Traceback (most recent call last):
2024-04-10 15:39:47       File "/service/processor/processor.py", line 173, in start_processing
2024-04-10 15:39:47         handler.process_event(
2024-04-10 15:39:47       File "/service/processor/handlers/shotgrid_event.py", line 42, in process_event
2024-04-10 15:39:47         hub.react_to_shotgrid_event(sg_payload["meta"])
2024-04-10 15:39:47       File "/service/ayon_shotgrid_hub/__init__.py", line 353, in react_to_shotgrid_event
2024-04-10 15:39:47         create_ay_entity_from_sg_event(
2024-04-10 15:39:47       File "/service/ayon_shotgrid_hub/update_from_shotgrid.py", line 126, in create_ay_entity_from_sg_event
2024-04-10 15:39:47         if sg_ay_dict["data"][sg_parent_field] is None:
2024-04-10 15:39:47            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
2024-04-10 15:39:47     KeyError: 'sg_sequence'
```

**Comment by jakubjezek001** [comment]
solved in #72
